### ISSUE TITLE
Rework the 'Setting the scene' episode

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/python-intermediate-development#62]
- Fix the narrative (link to slides)
- Remove the quiz and link to it
- Diagram that shows how different pieces relate and fix together, including tools that we used and "this is what developers do and how they use them (interchangeably)" and bring it back to reality (not just theoretical story, you will be using these things too)

**Comment by anenadic** [comment]
Do proposed changes in a Google doc for example to check the wording with @steve-crouch and @jag1g13.

**Comment by steve-crouch** [comment]
Done - closing.
